### ISSUE TITLE
use the interface prometheus.Registerer in parameter of the server

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/promql-langserver#163]
the method `CreateInstHandler` should take the interface `prometheus.Register` coming from the lib go_client.

Today it is taking directly an instance of the interface and so it cannot be used in prometheus.

**Comment by slrtbtfs** [comment]
AFAIK `CreateInstHandler` doesn't add any instrumentation that isn't already provided by the router used by Prometheus. Also we don't want the `/metrics` endpoint that is provided by CreateInstHandler there.

So `CreateHandler` should be used instead.

Since that isn't clear from the documentation I'm labeling this a docs issue for now.
