### ISSUE TITLE
Highlight correct argument when typing function calls

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/promql-langserver#166]
Currently the language server always highlights the first argument of a function in the signature help, even when typing the second or later argument.
![function_help](https://user-images.githubusercontent.com/538008/84796544-03947580-aff9-11ea-8d5d-9699198b8849.png)

The help popup should highlight the right function argument. I assume this is something in the language server rather than the VS Code extension.

**Comment by slrtbtfs** [comment]
Thanks for the bug report!

IMO it can be considered a bug both in the language server as well as in the library vendored from gopls.


At the moment the response given by the language server when a signature is requested does not indicate which argument should be highlighted.

https://github.com/prometheus-community/promql-langserver/blob/a4924518287f655bb4f8ee3dc92162d0f1cc76de/langserver/signature.go#L41-L43

Since gopls uses a float instead of a float pointer, this gets translated by the `gopls` lib to something like

```
[Trace - 20:55:15.188 PM] Received response 'textDocument/signatureHelp - (13)' in 0ms.
Result: {"signatures":[{"label":"abs(v instant-vector)","parameters":[{"label":"v instant-vector"}]}],"activeSignature":0,"activeParameter":0}
``` 
with `activeParameter` set to `0`.

The best way to fix this would be to set the `activeParameter` correctly.
